BACKEND = "vertex_ai"
GEMINI_MODEL = "gemini-2.5-pro"
GCP_PROJECT_ID = "prometheus-leadership-ai"
GCP_LOCATION = "europe-southwest1"

[gcp_service_account]
type = "service_account"
project_id = "prometheus-leadership-ai"
private_key_id = "c75546ff051765c9a95559849315c284eec0e9b2"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZqfkLP8GBxGKv
jBWXd9G5YTq7beDv1jbvYF/0CCo7cAJG6ibdR3c2Bvfy02Pk8Z0MIQYw0RKL06s5
3FefI+r73Yx3yq9uc6CnAVAzC77LDdJw6BE+V9v/Ykm7n6qCMEIH6R32o+WFbivj
SkWDhIfkjOdgXnZ5lYq4ZXd1H9AILkCRex0wMzMNY/Yyy/kJFeoH/jZZt1vt1kYr
68k1aVlKNqv1jAVBdTp+P9+sr1hiOg9WM79L4Xu3qBSB+Gq2wyKjOg1E46Lzcrtu
uKHJgpZnAU1NXwhUIxchPRTpro+41+QmHFLC1FTOGEH6pz5jJpvTxCM4cmLrUtOB
fl/ffB1zAgMBAAECggEAPRDhRIUqEnCY6TxJcHnWtoYvNpdgpJj6R5VHxkymII/P
q7qUlb8vlFJHLPKek4Qvtc/sDzUQ2XbUkoKdeJHYorno51DPgBLjjwcgy3lvmUMy
96c78zwuBgu6uO9WJHlKhTKjS+d2hMVAfd9/+iJsB7R6U4CdB4ZraUlaRttaf3iJ
wrXtVKYvmgGxQHr+QHBPJzAqmtUkSIZ84hfEf28JDzO88uFbvMcbg6bHkW9iCDEH
oIrQXzopVmMHMRx9CqCt04bOm9+SOZKjEXtVfCW9mhj6BJ9PZxynoyIzolUPIZbg
FmH6sBUMX1BYpa/7EHsnk4LA7Zyf1H/XJF2qXicSGQKBgQD7Ju7UUWTxDSXrNSIE
9WW3KTivPTJqx1XtdcXoYyM4tFr3yYGkgwVemdVVHPhWrf5ubl8/U19y9yraqHJv
NX+CNb48A5afYgLEXeb+wWfK8rdSoJ9UZbR29Dl5cLP0FTuhQ02tfrS8ry23en+/
MDywWSMtQqcU5coppYFMgQIpWQKBgQDd3Y723Hy70Bd1PmrkSfQNbHNCFHRNVX7b
ptSNGuBVnaMeGTnXNUKce2x7AZDn90I1tZwVg072eFHf88XuCh6pOzR1dN69iDja
2TtNCO/aGMjDRdSbuEw1/HAmOW400htmKC3NmA52WEivBVXfKlygNSPgBNn3fmnH
ng+Dhf+XqwKBgFxyzF8jRwDkUhzuhgNFQZfWeKMo57IehibOv3b3ZzOsT//+ENa5
0/QqtDiMXW2qxoln32+0BOKQ0RmD//unubP4jHoS6BLrRRF7b1g/YTF3frvPnFa4
yWEwLSfisJscZcLKv4EpruX1peJwGS4LV4uihCxY6J/spioGXj4HDwChAoGBAKzG
SPr9ITWxC1OGU/+Lh76cYfVnsFo45h1vgb6Q23pQ1CIwStbI5yKtCwGPaqT57Fmf
H/mw0+EkOb5JPC3vO4lWTbfaV0sJthzXZlLLTt1sx4sp6jOKBe9UspFRz/zaUfPv
/htI+po2jgOeCA1OE+u+9j0SChuuGfoVoMcvpqcZAoGANbIcEYyfl3LbIpiZsRZH
cLVdWwpsf7ULaM+S/4a+VRojzDBx3qE1H3XzihXXZNAUjun4u6Z5yFZ6fLLHTeLP
6CvVI3ZGG/+9Gc87JTlO9WwXdRlAnqv86CQ1VhIx/tClcrM6bEfKVFtTJO+Teq3/
j15kuRBc1UvSbln16xA6QII=
-----END PRIVATE KEY-----
"""
client_email = "vertex-express@prometheus-leadership-ai.iam.gserviceaccount.com"
client_id = "111222374271846368249"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vertex-express%40prometheus-leadership-ai.iam.gserviceaccount.com"
